### ISSUE TITLE
Content doesn't get copied to clipboard in some cases

### ISSUE THREAD

**Issue by novoid** [kuanyui/copy-as-org-mode#1]
Hi,

First of all, thank you for this awesome add-on! I'll create an account on one of those platforms just in order to show my gratitude for your tool!

Freshly installed on my Firefox 92.0 (64-bit) I noticed, that invoking your add-on onto a rather simple selection doesn't copy anything into the clipboard. Since it works some times, this seems to be an issue to solve.

Can you give me instructions how I can assist you in finding the underlying issue?

**Comment by kuanyui** [comment]
Please provide the URL where you encountered the issue and the add-on version you installed.

**Comment by novoid** [comment]
I installed your add-on today from https://addons.mozilla.org/en-US/firefox/addon/copy-as-org-mode/ and this is also the page I used to test the add-on initially.

My selection was:
```
About this extension
Copy selection or links as Emacs's Org-mode format text!

For source code and issue / bug report, please visit GitHub

    Yes, the 7-years-old Copy as Org-Mode which originally implemented on legacy Firefox is back! Finally rewritten as WebExtension, with much more features and customization!


Supports syntax: Inline emphasis marks, List, Code block & language detection, Table...etc
```

I re-tested it now and it still doesn't result in anything in the clipboard. Same holds true for the selection:
```
More information

Add-on Links

        Support site

Version
    0.0.2
Size
    161.23 KB
Last updated
    8 hours ago (Sep 29, 2021)
Related Categories

        Other

License
    Mozilla Public License, version 2.0
Version History

        See all versions
```
or
```
For source code and issue / bug report, please visit GitHub
```

I tries it several times. Actually, I was not able to make it work on that page at all.

On other pages, I succeeded: https://karl-voit.at/2020/08/14/project-mgt-draft/ with selection:
```
- Updates:
  - 2020-08-25: new section "Links" with [[https://plaindrops.de/blog/2020/GTDorgmode/][A simple GTD approach using Org mode and Org Edna | Plain DrOps]]
  - 2020-09-02: [[https://gitlab.com/joukeHijlkema/org-gantt/-/issues/6#note_405808449][Jouke found a solution to "how to achieve that a task is only scheduled when a set of other tasks is done completely?"]]
  - 2020-09-23: I found out that in contrast to the (now unmaintained) org-edna fork I was using until a few days ago, the original org-edna requires =ids(foo bar)= to have quotes like =ids("foo" "bar")= unless =uuidgen= IDs are used. So I adapted the example project below to meet this syntax. Good news: with org-edna v1.1.2 you can also use =ids("id:foo" "id:bar")=  and get navigatable IDs.
  - 2020-09-26:
    - Comments from yantar92
    - Link to =org-linker-edna=
  - 2021-09-20: =org-linker-edna=  proves to solve the issue of linking headings

I'm currently dreaming of a workflow that allows complex project management within [[https://karl-voit.at/orgmode][Org mode]]. Please do read [[https://karl-voit.at/2019/11/03/org-projects][my article how I define projects within Org mode]]. I won't repeat those things in this article here.
```

**Comment by kuanyui** [comment]
This is not a bug at all.

Because Firefox forbids **ALL extensions** to run under some specially reserved domains, for example, Mozilla Add-on (https://addons.mozilla.org/). Maybe I should add some warning message about this.

Is there any other page has similar issues?

**Comment by novoid** [comment]
Oh, then this would explain the issue. I'm sorry, I didn't know that and a warning would be cool since that page is the first page you can use to test the add-on after installing it via browser.

So far, I had no issue with another page but I'll observe it in the upcoming decades, I guess ;-)

**Comment by kuanyui** [comment]
I also don't know this restriction until I wrote a WebExtension, I even
frequently forget this restriction when writing WebExtension and feel
confused why is it not work.

As far as I know, I have to add `tab` permission merely for implementing
this stupid feature... I guess adding a warning message in Mozilla Addon
page is enough.



2021年9月29日(水) 20:44 Karl Voit ***@***.***>:
