### ISSUE TITLE
Does not work on webmail pages (with frames, tables, etc.)

### ISSUE THREAD

**Issue by liar666** [kuanyui/copy-as-org-mode#10]
Hi,
Thanks for the tool.
Unfortunately, it does not work on my institution's Webmail ("Partage"), which is composed of frames, tables, etc.
When I select some content inside an email (see selected table in picture below), and hit "copy-selection-as-org", I only get the URL of the page copied (see the "save-as-org" tooltip content in the image):

![screenshot_2023-10-17-11 08](https://github.com/kuanyui/copy-as-org-mode/assets/3216927/97a32ef7-5977-4b11-9683-ee8495e1a3b1)

I've tried to "Open this frame in a new tab" to get a page with only the email content, but the webmail software does not work correctly: the whole page is reloaded...

**Comment by kuanyui** [comment]
I don't sure how frame will be handled. Have you tried right-click on the selected range instead of clicking on the toolbar icon?

**Comment by kuanyui** [comment]
No response, donno what do you want.
