### ISSUE TITLE
Feature wish: copy multiple window/tab titles when multiple Firefox tabs are selected

### ISSUE THREAD

**Issue by novoid** [kuanyui/copy-as-org-mode#11]
Hi,

I don't know if this is a big thing to implement or a small extension:

When I select more than one Firefox tab (e.g., using Ctrl-click on multiple tabs), I'd like to get an Org-mode list of those tabs copied to the clipboard when I press the "copy-as-org-mode" button.

**Comment by kuanyui** [comment]
1. How to "select multiple tabs" in Firefox? I never heard of such feature in Firefox.
2. Grab title and url of all tabs and convert to org-mode should be very easy, please consider to make a PR.

**Comment by kuanyui** [comment]
About `Ctrl+Click on tab`,  I never know such feature exist in Firefox / Chromium. 

1. To implement this, an additional permission `tabs` may be added.
2. Take a look of the API reference of `tabs.query()` https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query , maybe it can do this.

**Comment by kuanyui** [comment]
And last but not the least, don't expect me to implement in foreseeable future (unless maybe someday I'm in a good mood), because I don't need this feature. If you need this feature urgently, please consider to make a PR.

**Comment by novoid** [comment]
Oh, I don't have JavaScript knowledge myself. Greetings from Graz/Austria!

**Comment by kuanyui** [comment]
If nobody want to do this, close as wontfix.
