### ISSUE TITLE
cannt build it locally

### ISSUE THREAD

**Issue by Aneeqasif** [kuanyui/copy-as-org-mode#12]
hi there i want to do minor adjestments but i cannot build it in github codespaces i am not a expert i just want to change the right click menu item title as it is too long and make the menu too wide i just want to replace it with smaller text like "Orgmode: Copy URL" instead of full verbose title like `Copy current page title and URl as orgmode`

Please Guide

**Comment by kuanyui** [comment]
Please provide the error message you've encounter otherwise it's impossible for me to guess what the issue you've encountered

**Comment by kuanyui** [comment]
Close due to no response.
