### ISSUE TITLE
[feature] Chrome version?

### ISSUE THREAD

**Issue by hrehfeld** [kuanyui/copy-as-org-mode#2]
I know this is a big request, but many extensions seem to work for both browsers.

Maybe we can use this thread to collect information regarding a conversion.

Is there anything making this impossible in the first place?

**Comment by kuanyui** [comment]
It's not difficult but I guess I personally will never do it because I basically don't use Chromium nor Edge.

[Someone had ever asked me to port my another add-on to Chrome, but I don't want to.](https://github.com/kuanyui/BooruOneClickDownloader/issues/1) 

> "Making" / porting extension for Chrome is not difficult, but "deploying" to Chrome Store would not be a good experience, I also don't want to argue nor fight with Google's policies and rules and its users and disgusting and low-quality malicious comments, it brings me nothing except for upset and sad mood. And I don't use Chrome as my primary browser due to privacy concern, so... no.

And my free time is precious so I won't waste my time to implement what I needn't, especially for free.

If anyone need, please consider to make a PR.

**Comment by hrehfeld** [comment]
I wasn't really expecting you to develop it, sorry! But maybe we can leave the thread open so we can collect info?

**Comment by kuanyui** [comment]
I mean, technically, there should nothing or special info need to be
collected or discussed at all. All what needed, in fact, is merely free
time and make a PR. As far as I know, this project doesn't use any
Firefox-specific API.

The only things need to be noticed specially and tested... should be:

1. The string process of contenteditable in option_ui which seems not
 standardized yet, I guess. 
2. And some newlines in Node.innerText or Node.textContent may be
disappeared in some situations for unknown reasons, which I should have
solved and tested under Firefox but not on other browsers yet.
3. CSS for options_ui is for Firefox, which may looks odd under other 
browsers.

If want to make a PR for this, please make sure:
1. Solve and test the above mentioned issues carefully.
2. Keep code clean (though it should not need too many modifications.)
3. Create separate `manifest.json` files for each browsers, and copy
the corresponding `manifest.json` when building via Makefile.

2021年10月11日(月) 0:18 Hauke Rehfeld ***@***.***>:

**Comment by hrehfeld** [comment]
Awesome, that's a good place to start, thanks for the info!
