### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by vzaliva** [kuanyui/copy-as-org-mode#3]
This extension uses the same icon as https://github.com/sprig/org-capture-extension 
It is confusing to have 2 exactly the same icons in the toolbar.

**Comment by kuanyui** [comment]
I like this unicorn so I don't want to change it... And not interested to
make an icon for it, bacause I install my own addon only, won't be
confusing for me.

2021年11月6日(土) 1:19 Vadim Zaliva ***@***.***>:

**Comment by kuanyui** [comment]
But if need, maybe can make an option to change icon...

**Comment by tecosaur** [comment]
Hey, the unicorn is definitely good, but IMO it has a bit too much detail for the size it is in the toolbar/context menu. If you'd be interested in a less-detailed version, I have a few variants on hand.

![image](https://user-images.githubusercontent.com/20903656/140682259-62c56cfc-482f-4b09-b1b8-fc50269d5f58.png)
 
###### NB: The visual weirdness in the last two is a glitch in the rendering in the file manager, as is not actually part of the image

**Comment by kuanyui** [comment]
> Hey, the unicorn is definitely good, but IMO it has a bit too much detail for the size it is in the toolbar/context menu. If you'd be interested in a less-detailed version, I have a few variants on hand.
> 
> ![image](https://user-images.githubusercontent.com/20903656/140682259-62c56cfc-482f-4b09-b1b8-fc50269d5f58.png)
> ###### NB: The visual weirdness in the last two is a glitch in the rendering in the file manager, as is not actually part of the image

Hi, I cannot feel in such icon size, the simplified variants in this way could improve its identifibility, and still looks nearly same with the original icon.

**Comment by kuanyui** [comment]
In fact, the icon is not important for copy-as-org-mode. Because its function can be simply triggered via keyboard. You can hide it from the addon icon bar.

If no other comment or PR, I want to close this issue.
![Screenshot_20211210_113012](https://user-images.githubusercontent.com/1370070/145512616-1ce3bcbf-91f9-453b-8791-acdf6243144d.png)

**Comment by tecosaur** [comment]
Yea, it's definitely not important, but I do think it would be a little nicer to use a simplified icon. Just let me know if you're interested in any of the files I shared a screenshot of earlier.

**Comment by vzaliva** [comment]
I understand you are using only one extension and do not care about other users' experience but I am still not happy as my toolbar looks like the following:

![image](https://user-images.githubusercontent.com/86581/145628326-cfa946c6-5822-4a9e-8aa7-c7574c7325a5.png)

Allowing icon customization would be helpful.
