### ISSUE TITLE
support org-protocol

### ISSUE THREAD

**Issue by yuzhou721** [kuanyui/copy-as-org-mode#4]
Do you plan to add org-protocol support？

**Comment by kuanyui** [comment]
No. I've never used it and don't want to spend my time to understand what it exactly is. Too many new cool-looking tools but my time is limited.

**Comment by tianheg** [comment]
@yuzhou721 You could use this https://github.com/vifon/org-protocol-for-firefox

**Comment by yuzhou721** [comment]
> @yuzhou721 You could use this https://github.com/vifon/org-protocol-for-firefox

@tianheg This extension is nice, but I would like to be able to save the converted documents via org-protocol
